# Used to pull the dotnet latest docker image, resotre and build
# the solution. Then run tests.

image: mcr.microsoft.com/dotnet/core/sdk:2.2.402

stages:
  - test 

before_script:
  - "dotnet restore ./ArgumentExtractionCore"

build:
  stage: test
  script:
    - "dotnet build ./ArgumentExtractionCoreTests"
    - "dotnet build ./ArgumentExtractionCore"
    - "dotnet test --logger:\"xunit;LogFilePath=test_results.xml\" --collect:\"XPlat Code Coverage\""
  artifacts:
    when: always 
    paths:
      - $TESTPROJECTDIR/test_results.xml
      - $TESTPROJECTDIR/TestResults/*/*.xml
    reports:
      junit: $TESTPROJECTDIR/test_results.xml
    expire_in: 3 days
  coverage: '/line-rate\="[0-9]\.[0-9]*"/'
